config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'rooms/show'

  devise_for :users
  root 'static_pages#index'
  get 'home', to: 'static_pages#home'
  get 'follow', to: 'static_pages#follow'
  get 'follow_user', to: 'static_pages#follow_user'
  post 'follow_user', to: 'static_pages#follow_user'
  post 'block_user', to: 'static_pages#block_user'
  post 'deep_block_user', to: 'static_pages#deep_block_user'
  get 'users', to: 'users#show_all'

  resources :users, only: [:show] do
    get 'requesting', to: 'users#requesting'
    get 'requested', to: 'users#requested'
    resources :friends, only: [:index]
  end

  resources :friend_rooms, only: [:show]
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :from_user, class_name: "User"
  belongs_to :to_user, class_name: "User"
  validates :from_user_id, presence: true
  validates :to_user_id, presence: true
  has_many :personal_messages, dependent: :destroy
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  before_action :private_user

  def index
  end

  private
  def private_user
    if not current_user == @user = User.find_by(id: params[:user_id])
      redirect_to user_friends_url(:user_id => current_user.id)
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.slim
- content_for :title, 'Friends | LineLight'
h2 #{@user.username}の友達

- @user.friends.each do |friend|
  = link_to "#{friend.username}", user_path(id: friend.id)
  = button_to "トーク", friend_room_path(id: Friend.find_by(from_user_id: @user.id, to_user_id: friend.id).id), { method: :get }
  = button_to "ブロック", deep_block_user_path(params: {email: friend.email}), data: {confirm: "本当に「#{friend.username}」をブロックしますか？",
    cancel: "やめる",
    commit: "ブロックする"}, title: "ブロックの確認"