config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'rooms/show'

  devise_for :users
  root 'static_pages#index'
  get 'home', to: 'static_pages#home'
  get 'follow', to: 'static_pages#follow'
  get 'follow_user', to: 'static_pages#follow_user'
  post 'follow_user', to: 'static_pages#follow_user'
  post 'block_user', to: 'static_pages#block_user'
  post 'deep_block_user', to: 'static_pages#deep_block_user'
  get 'users', to: 'users#show_all'

  resources :users, only: [:show] do
    get 'requesting', to: 'users#requesting'
    get 'requested', to: 'users#requested'
    resources :friends, only: [:index]
  end

  resources :friend_rooms, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable
  has_many :messages, dependent: :destroy
  has_many :from_friendships, class_name: "Friend", foreign_key: :from_user_id, dependent: :destroy
  has_many :follows, through: :from_friendships, source: 'to_user'
  has_many :to_friendships, class_name: "Friend", foreign_key: :to_user_id, dependent: :destroy
  has_many :followers, through: :to_friendships, source: 'from_user'

  def follow(target)
    if self.id != target.id
      Friend.create(from_user_id: self.id, to_user_id: target.id)
    end
  end

  def block(target)
    Friend.find_by(from_user_id: self.id, to_user_id: target.id).destroy
  end

  def deep_block(target)
    self.block(target)
    Friend.find_by(from_user_id: target.id, to_user_id: self.id).destroy
  end

  def friends
    friends = []
    self.follows.each do |follow_user|
      if follow_user.follows.include?(self)
        friends << follow_user
      end
    end
    friends
  end

  def friend_with?(target)
    if User.find_by(id: target.id)
      self.follows.include?(target) && self.followers.include?(target)
    end
  end

  def requesting_users
    requesting_users = []
    self.follows.each do |follow_user|
      if not follow_user.follows.include?(self)
        requesting_users << follow_user
      end
    end
    requesting_users
  end

  def requested_users
    requested_users = []
    self.followers.each do |followed_user|
      if not self.follows.include?(followed_user)
        requested_users << followed_user
      end
    end
    requested_users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:show_all]
  before_action :friend_user, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def show_all
    @users = User.all
  end

  def requesting
    if not current_user == @user = User.find_by(id: params[:user_id])
      redirect_to user_requesting_url(:user_id => current_user.id)
    end
  end

  def requested
    if not current_user == @user = User.find_by(id: params[:user_id])
      redirect_to user_requested_url(:user_id => current_user.id)
    end
  end

  private
  def admin_user
    if not current_user.admin_flg?
      redirect_to user_url(:id => current_user.id), :alert => '管理者権限がありません'
    end
  end

  def friend_user
    if not current_user.admin_flg?
      if target = User.find_by(id: params[:id])
        if current_user == target
          redirect_to home_url
        elsif not current_user.friend_with?(target)
          begin
            redirect_to :back, :alert => '友達ではないユーザの情報は見れません'
          rescue ActionController::RedirectBackError
            redirect_to_user_friends
          end
        end
      end
    end
  end

  def redirect_to_user_friends
    redirect_to user_friends_url(:user_id => current_user.id), :alert => '友達ではないユーザの情報は見れません'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/requested.html.slim
- content_for :title, '友達リクエスト | LineLight'
h2 友達リクエスト

.requested-info-area
  - if @user.requested_users.count == 0
    h4 友達リクエストはありません
  - else
    ul.requested-list
      - @user.requested_users.each do |user|
        li.requested-item
          .requested-row
            .requested-info
              = "#{user.username} (#{user.email})"
            = button_to "承認", follow_user_path(params: {email: user.email}), method: :post, class: "btn btn-success approve-button"
            = button_to "拒否", block_user_path(params: {email: user.email}), data: {confirm: "本当に「#{user.username}」からのリクエストを拒否しますか？",
              cancel: "やめる",
              commit: "拒否する"}, title: "リクエスト拒否の確認",
              class: "btn btn-danger reject-button"

app/views/users/requesting.html.slim
- content_for :title, '友達申請中ユーザ | LineLight'
h2 友達申請中ユーザ

.requesting-info-area
  - if @user.requesting_users.count == 0
    h4 友達申請中のユーザはいません
  - else
    ul.requesting-list
      - @user.requesting_users.each do |user|
        li.requesting-item
          .requesting-info
            = "#{user.username} (#{user.email})"

app/views/users/show.html.slim
- content_for :title, "User:#{@user.id} | LineLight"
h2 #{@user.username}のプロフィール

= @user.email

app/views/users/show_all.html.slim
- content_for :title, 'Users | LineLight'
h2 ユーザ一覧

- @users.each do |user|
  p
    = "#{user.id}: "
    = link_to "#{user.username}", user_path(id: user.id)