config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'rooms/show'

  devise_for :users
  root 'static_pages#index'
  get 'home', to: 'static_pages#home'
  get 'follow', to: 'static_pages#follow'
  get 'follow_user', to: 'static_pages#follow_user'
  post 'follow_user', to: 'static_pages#follow_user'
  post 'block_user', to: 'static_pages#block_user'
  post 'deep_block_user', to: 'static_pages#deep_block_user'
  get 'users', to: 'users#show_all'

  resources :users, only: [:show] do
    get 'requesting', to: 'users#requesting'
    get 'requested', to: 'users#requested'
    resources :friends, only: [:index]
  end

  resources :friend_rooms, only: [:show]
end

app/views/layouts/_footer.html.slim
footer.footer
  div.container
    nav
      ul
        li
          = link_to 'プロフィール編集', edit_user_registration_path
        li
          = link_to 'ログアウト', destroy_user_session_path, method: :delete
        - if current_user && current_user.admin_flg?
          li
            = link_to 'ユーザ一覧', users_path

app/views/layouts/_header.html.slim
header class=["nav", "navbar-inverse"]
  div.container
    = link_to 'Line Light', root_path, id: 'logo'
    nav
      ul class=["nav", "navbar-nav", "navbar-right"]
        - if user_signed_in?
          li class="nav-item #{'active' if controller.controller_name == 'static_pages' && controller.action_name == 'home'}"
            = link_to 'ホーム', home_path, class: "nav-link"
          li class="nav-item #{'active' if controller.controller_name == 'rooms' && controller.action_name == 'show'}"
            = link_to 'チャットルーム', rooms_show_path, class: "nav-link"
          li class="nav-item #{'active' if controller.controller_name == 'static_pages' && controller.action_name == 'follow'}"
            = link_to 'フォロー', follow_path, class: "nav-link"
          li class="nav-item #{'active' if controller.controller_name == 'users' && controller.action_name == 'requesting'}"
            = link_to "友達申請中 (#{current_user.requesting_users.count})", user_requesting_path(:user_id => current_user.id), class: "nav-link"
          li class="nav-item #{'active' if controller.controller_name == 'users' && controller.action_name == 'requested'}"
            = link_to "友達リクエスト (#{current_user.requested_users.count})", user_requested_path(:user_id => current_user.id), class: "nav-link"
        - else
          li
            = link_to 'サインアップ', new_user_registration_path
          li
            = link_to 'ログイン', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for?(:title) ? yield(:title) : 'LineLight'
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/header'
    div.container.body_container
      - flash.each do |message_type, message|
        - if message_type == :timedout
          next
        - elsif message_type == 'notice'
          div class=["flash", "alert-success"]
            = "#{message}"
        - elsif message_type == 'alert'
          div class=["flash", "alert-danger"]
            = "#{message}"
      = yield
    = render 'layouts/footer'